version: '3'
services:
  app:
    build: .
    hostname: visao-dev
    networks:
      - visao
    environment:
      IS_DOCKER: "true"
      PORT_DOCKER: 3000
      API_PORT: 3000
    ports:
      - 3000:3000

networks:
  visao:
    driver: bridge
